name: env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - double-conversion=3.3.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - freetype=2.13.3
  - graphite2=1.3.14
  - harfbuzz=11.4.3
  - icu=75.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcups=2.3.3
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.2
  - packaging=25.0
  - pandas=2.3.2
  - pcre2=10.45
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.1
  - readline=8.2
  - scipy=1.13.1
  - setuptools=80.9.0
  - six=1.17.0
  - tk=8.6.13
  - tornado=6.5.2
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wayland=1.24.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zstd=1.5.7
  - pip:
      - albucore==0.0.23
      - albumentations==2.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - coloredlogs==15.0.1
      - defusedxml==0.7.1
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fsspec==2025.7.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.6
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnx==1.14.0
      - onnxruntime-gpu==1.18.0
      - opencv-python-headless==4.10.0.84
      - protobuf==6.32.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - seaborn==0.13.2
      - simsimd==6.5.1
      - stringzilla==3.12.6
      - supervision==0.25.1
      - sympy==1.14.0
      - tifffile==2025.5.10
      - tokenizers==0.20.3
      - torch==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - transformers==4.46.3
      - triton==2.2.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - ultralytics==8.3.63
      - ultralytics-thop==2.0.16
      - urllib3==2.5.0
